
<div class="welcome_logo">

<img class="logo_green" src="../../../../../public/images/logogreen.png" alt="logogreen"> 


</div>

<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Čističky odpadních vod</h2>
<p></p>
</div>


<div class="main_page_text">
  <p>Věnujeme se montážím jak samotných ČOV, tak montážím čerpadel do již stávajících.</p>
</div>



<div class="fotky">




</div>

<div class="bckbtn">
<a class="back" href="montaze-servis">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>

</div>