<div class="welcomeimg2">

<h4><span>Individuální</span> přístup</h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
    <a class="soc-but">
    <i id="mobile" class="fa-solid fa-mobile-screen"></i>
    <i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


    <div class="welcome_logo">

        <img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

    </div>


<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Úpravna vody</h2>
<p>Čistá voda – čistý život</p>
</div>


<div class="main_page_text">

<p>V oboru úpravy vod a filtrace vody spolupracujeme se společností <b>Univerzální čistá voda, a.s..</b> Tato firma patří mezi špičky na trhu s dlouholetou historii.  Kvalitní výrobky od našeho dodavatele, montujeme zprovozňujeme a servisujeme přímo u Vás na adrese. Můžeme Vám nabídnout kompletní technickou podporu s různými řešeními přímo na míru dle vašich potřeb.</p>
<p>V případě že nemáte dostatečně vydatný přítok ve vaší studni ( vrtané, kopané ), Vám navrhneme kompletní řešení včetně samotné realizace na klíč. Máte tedy možnost se v tomto směru stát takzvaně soběstační. V dnešní  době cen vodného a stočného, brzká návratnost.</p>
<p id="ucv"><a id="ucv-a" href="https://www.ucv.cz"><img src="/public/images/univerzalnivoda.png" alt="">www.ucv.cz</a></p>
<p style="margin-top: 2rem;margin-bottom:2rem;"><b style="font-size:1.22rem;color: #c60707;">Voda je extrémně tvrdá, železitá, zapáchá nebo obsahuje nadměrné množství dusičnanů?</b></p>
<br><br>
<p><b style="font-size:1.5rem; color:#00288d;">CO PRO VÁS MŮŽEME UDĚLAT:</b></p><hr><br><br>
<p>Formou písemné nabídky Vám navrhneme různá řešení, která budou ušita přímo „na míru“ pro Vaši potřebu. Vy si pak sami můžete zvolit, které řešení bude vyhovovat Vašim požadavkům a odpovídat Vašim možnostem.</p>
<p>Můžete nás navštívit, filtrační zařízení si zde prohlédnout a konzultovat možnosti jejich užití. Můžete přijít každé pondělí od 8.30 do 16.00 hodin k nám na prodejnu v Příboře, v jiné době po dohodě. Rádi Vám podáme vyčerpávající informace a odpovíme na všechny Vaše dotazy.</p>
<p>Nabídku pro Vás vypracujeme ZDARMA, stejně jako veškeré porady a konzultace. Filtrační zařízení si u nás můžete zakoupit nebo Vám je můžeme zaslat na dobírku. Odbornou montáž zajišťujeme. Na zařízení poskytujeme dostatečnou záruku, záruční i pozáruční servis zajišťujeme.</p>
<br><br><br>
<p><b style="font-size:1.5rem; color:#00288d;">JAK POSTUPOVAT PŘI VÝBĚRU VHODNÉHO FILTRAČNÍHO ZAŘÍZENÍ?</b></p><hr><br><br>
<p>Nepřistupujte k problému úpravy vody neprofesionálně. Vyplatí se Vám zadat svůj problém odborné firmě, která Vám k příslušným technologiím poskytne plné záruky.</p>
<p>Prvním stupněm úpravy je především zajištění čistoty vodního zdroje. Plocha okolo studny nesmí být jakkoli znečišťována.</p>
<p>Potřebujete znát kvalitu vody ve Vaší studni, abyste věděli, které nežádoucí látky a v jakém množství jsou ve vodě obsaženy. Proto je nutné nechat si udělat rozbor vody.</p>
<p>Podle charakteru znečištění a laboratorního rozboru můžete zvolit vhodný druh filtru. Neexistuje univerzální filtr, který by z vody o neznámém složení dokázal vyrobit vodu.</p>
<p>Nezapomínejte, že filtr musí kapacitně vyhovovat Vašim potřebám. Celková spotřeba na osobu se pohybuje v rozmezí 150 až 250 litrů denně, pitné vody 2 až 5 litrů denně.</p>
<p>Filtry musí vyhovovat po hygienické i bezpečnostní stránce. Zásadně si vybírejte pouze filtry, které jsou schváleny k používání pro pitnou vodu dle platných zákonů a předpisů. Námi dodávaná zařízení byla testována po všech stránkách a těmto předpisům vyhovují.</p>
<p>Dobře zvažte, zda si dokážete filtr namontovat sami. Pokud si tím nejste zcela jisti, odbornou montáž můžeme zajisti.</p>
<p>Filtr jako každé jiné zařízení vyžaduje svoji kontrolu a údržbu, spočívající hlavně v občasném promytí filtru. Toto promytí je možno provádět ručně nebo nůže být částečne nebo plně automatizováno.</p><br><br>
<p><b style="font-size:1.22rem;color: #c60707;">Zajišťujeme komplexní služby v oblasti úpravy a filtrace vody pro pitné, užitkové i technické účely – vhodné pro rodinné domy, chaty, stravovací a ubytovací zařízení, kostelny, prádelny, obce i průmysl.</b></p>
<br><br><br>
<p><b style="font-size:1.5rem; color:#00288d;">CO OD VÁS POTŘEBUJEME ZNÁT</b></p><hr><br><br>
<p><b>ROZBOR VODY:</b></p>
<p>Pokud rozbor vody máte, zašlete nám jej. Pokud rozbor vody nemáte, doneste nebo zašlete poštou litr vody ve vymyté a uzavřené plastikové lahvi, orientační rozbor v základních ukazatelích provedeme. Též Vám můžeme doporučit akreditovanou laboratoř v blízkosti Vašeho bydliště, která tyto rozbory provádí.</p>
<p><b>POTŘEBA VODY:</b></p>
<p>Uvádí se v m3/den nebo v l/sec. Pokud ji nedokážete odhadnout, stačí přibližné údaje, např. rodinný domek 4 osoby, penzion 20 lůžek apod.</p>
<p><b>POŽADOVANÁ KVALITA:d</b></p>
<p>Požadavek např. v kvalitě vody pitné dle příslušné Vyhlášky, postačí pouze jako voda užitková, voda pro teplovodní systémy ap.</p>
<br><br>
    <h2 style="text-align: center;margin-bottom:4rem;font-size:2.5rem;font-family: 'Solitreo', cursive;color: #c60707;font-weight:600">Jaký je postup?</h2>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">1.</span> Rozbor vody</b></p>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">2.</span> Zaměření na stavbě</b></p>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">3.</span> Zpracujeme návrh celého systému</b></p>    
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">4.</span> Cenová kalkulace na kompletní realizaci</b></p>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">5.</span> Samotná realizace</b></p>   
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">6.</span> Uvedení do provozu</b></p>   
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">7.</span> Servis</b></p><br><br>
</div>


<div class="gallery">


<a href="/public/images/upravny-vody/1.jpg" rel="lightbox[galerie]">
<img src="/public/images/upravny-vody/1.jpg" alt="text">
</a>
<a href="/public/images/upravny-vody/2.jpg" rel="lightbox[galerie]">
<img src="/public/images/upravny-vody/2.jpg" alt="text">
</a>
<a href="/public/images/upravny-vody/3.jpg" rel="lightbox[galerie]">
<img src="/public/images/upravny-vody/3.jpg" alt="text">
</a>
<a href="/public/images/upravny-vody/4.jpg" rel="lightbox[galerie]">
<img src="/public/images/upravny-vody/4.jpg" alt="text">
</a>

</div>





<div class="bckbtn">
<a class="back" href="codelame">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>
</div>