<div class="welcomeimg3">
<img src="/public/images/novazelena.png" alt="">
<h4>Dotační programy <span>na klíč!</span> </h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

</div>

<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Program Dešťovka</h2>
<p>Kompletní vyřízení na klíč</p>
</div>


<div class="main_page_text">
    <p>Poradíme Vám, jak lze naložit s dešťovou vodou. Přímo u Vás navrhneme celý systém pro využití dešťové vody jak v domě, tak pro zahradu. Navrhneme Vám správný typ a velikost nádrže, celý systém nastrojíme <b> naší čerpací technikou </b> provedeme uvedení do provozu. Montáž nádrží na dešťovou vodu provádíme napříč Moravskoslezským krajem a na Moravě.</p>
    <p>Pomoci s profinancováním Vám mohou pomoci<b> státem poskytované dotace.</b> I v tomto případě se na nás můžete spolehnout. Zpracujeme Vám kompletní projekt, který následně předložíme na patřičný Úřad životního prostředí. Po samotné realizaci Vám bude vyplacena dotace ve vyměřené výši Ministrem životního prostředí.</p>
    <p>Montáže jímek provádíme na klíč včetně výkopových prací. Jsme schopni proto garantovat vysokou kvalitu a bezproblémový chod celého ústrojí.</p>
    <p><b>Výsledkem využití dešťové vody je jak vysoká úspora pitné vody tak i stejně vašich financí.</b></p>
    <br><br>
    <h2 style="text-align: center;margin-bottom:4rem;font-size:2.5rem;font-family: 'Solitreo', cursive;color: #c60707;font-weight:600">Jaký je postup?</h2>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">1.</span> Vypracování projektové dokumentace</b></p>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">2.</span> Vyřízení dotací na úřadě</b></p>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">3.</span> Provedení výkopových prací</b></p>    
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">4.</span> Dodání a ustavení nádrže</b></p>
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">5.</span> Nastrojení čerpací technikou</b></p>   
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">6.</span> Uvedení do provozu</b></p>   
    <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">7.</span> Vrácení dotace</b></p><br><br>

    <p>Na montáže retenčních nádrží poskytujeme 2 letou záruku.</p> 
    <p><b>Výše dotace závisí na typu využití dešťové vody.</b></p>
</div>

<div class="gallery">


                    <a href="/public/images/destovka/1.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/1.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/2.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/2.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/3.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/3.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/4.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/4.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/5.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/5.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/6.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/6.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/7.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/7.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/8.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/8.jpg" alt="text">
					</a>
                    <a href="/public/images/destovka/9.jpg" rel="lightbox[galerie]">
						<img src="/public/images/destovka/9.jpg" alt="text">
					</a>

                   

</div>



<div class="bckbtn">
<a class="back" href="programy">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>
</div>