<div class="welcomeimg">

<h1><span>Čistá voda</span> od Beskyd po Jeseníky.</h1>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 


</div>

<div class="welcome_text">
<h2>Vítáme Vás</h2>
<p>Na stránkách specialistů na vodní zdroje a čerpací techniku.</p>
</div>


<div class="main_page_text">
    <p><strong style="font-weight: 500;">V oblasti hospodaření s vodou a čerpací technikou se pohybujeme už řadu let. Poskytujeme prodej, montáž, servis zařízení které slouží k využití podzemních, srážkových, kalových a jiných vod.</strong></p>
    <p><strong style="font-weight: 500;">Naše práce začíná u čištění vodních zdrojů, přes úpravu vody, až po její využití v domácnosti, výrobní hale, či na zahradě. </strong></p>
    <p><strong style="font-weight: 500;">Disponujeme širokým sortimentem čerpadel a příslušenství, které naleznete při osobním kontaktu na prodejních místech, tak na eshopu.</strong></p>
    <p><strong style="font-weight: 500;">Podzemní, či srážkové vody jsou důležitým zdrojem, který se snažíme využít v prospěch našich zákazníků. Všechny oblasti naší práce naleznete v odkazech.</strong></p>


</div>


<div class="icons">
    <div>
        <i class="fas fa-arrow-alt-circle-up"></i>
        <h4>15 let na trhu!</h4>
    </div>
    <div>
        <i class="fa-solid fa-house-circle-check"></i>
        <h4>Kamenná prodejna</h4>
    </div>
    <div>
        <i class="fa-solid fa-screwdriver-wrench"></i>
        <h4>Montážní práce</h4>
    </div>

    <div>
        <i class="fas fa-handshake"></i>
        <h4>Individualní přístup</h4>

    </div>

</div>



<h3>Naše práce:</h3>




<div class="odkaz">

    <a href="destovka" id="destovka"><p>dešťovka</p></a>
    <a href="montaze" id="montaze"><p>Montáže</p></a>
    <a href="servis" id="btn-servis"><p>Servis</p></a>
    <a href="cisteni-vrtu" id="cisteni-vrtu"><p>čištění&nbspvrtů</p></a>    
    <a href="cisteni-studni" id="cisteni-studni"><p>čištění&nbspstudní</p></a>      
    <a href="comming-soon" id="prodej"><p>E&nbspshop</p></a>



</div>