<div class="welcomeimg2">

<h4><span>Individuální</span> přístup</h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
    <a class="soc-but">
    <i id="mobile" class="fa-solid fa-mobile-screen"></i>
    <i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


    <div class="welcome_logo">

        <img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

    </div>

    <div class="welcome_text">
        <h2 style="margin-bottom: 3px;">Montáže</h2>
        <p></p>
    </div>

    <div class="img-mapa">
        <img src="/public/images/mapa-blue.png" alt="mapa">
    </div>


    <div class="main_page_text" style="margin-top: 5rem; margin-bottom:3rem">
    <p>Provádíme montáže nových čerpadel, domácích vodáren, nádrží na dešťovou vodu a ČOV na zakázku, včetně zemních a instalatérských prací. Poskytujeme servis i na stávající vodní systémy, domácí vodárny, čerpadla apod. Věnujeme se doinstalovávání filtrů, řídících jednotek a všech potřebných příslušenství.</p>
    <p><b>Na montáže poskytujeme dvouletou záruku.</b></p>
   

</div>

    <div class="odkaz3">


    <a id="cerpadla-rozklik"><p>Čerpadla</p><i id="krizek-cerpadla" class="fas fa-times"></i></a>
    <a id="rucnipumpy-rozklik"><p>Ruční&nbsppumpy</p><i id="krizek-pumpy" class="fas fa-times"></i></a>
    <a id="retencninadrze-rozklik"><p>Retenční&nbspNádrže</p><i id="krizek-nadrze" class="fas fa-times"></i></a>

    <a id="filtrace-rozklik"><p>Filtrace</p><i id="krizek-filtrace" class="fas fa-times"></i></a>
    <a id="zahlavi-rozklik"><p>Záhlaví&nbspvrtů</p><i id="krizek-zahlavi" class="fas fa-times"></i></a>
    <a id="vodarny-rozklik"><p>Domácí&nbspvodárny</p><i id="krizek-vodarny" class="fas fa-times"></i></a>
    
    <div class="text1">
        <p>Provádíme montáže veškerých druhů čerpadel, které máme v nabídce od českých i zahraničních výrobců. Montujeme čerpadla do studní a vrtů, retenčních a přečerpávacích nádrží pro širokou škálu užití.</p>
        <p><img src="/public/images/vyrobci.png" alt="vyrobci"></p>
        <p>Čerpací techniku montujeme na potřeby a přání zákazníků. Můžete si vybrat jak z českým, tak zahraničních výrobců, za jejíž kvalitou a spolehlivostí si stojíme!</p>
        <p>Montujeme všechny druhy čerpadel které prodáváme a poskytujeme na ně jak záruční, tak pozáruční servis.</p>
        <p>Tvoříme domácí vodárny a jsme pro Vás schopni zajistit dodávku vody z jakéhokoli vodního zdroje na jakékoli užití, ať už se jedná o zásobování objektů, postřiky zemědělských ploch, nebo zavlažování zahrad.</p>
        <b>Montáže:</b><br><br>
        <strong>Ponorných čerpadel do vrtů</strong><br>
        <strong>Ponorných čerpadel do studní</strong><br>
        <strong>Čerpadel do jímek na dešťovou vodu</strong><br>
        <strong>Samonasávacích čerpadel</strong><br>
        <strong>Domácích vodáren</strong><br>
        <strong>Automatických tlakových stanic</strong><br>
        <strong>Snímačů hladin a hladinových sond</strong><br>
        <strong>Příslušenství k čerpadlům a vodárnám</strong><br>
        <br><br>
        <!--<a href="produkty/index">Nabídku našich domácích vodáren naleznete v kamenné prodejně, a již brzy taky na eshopu!</a>-->    
    

        <div class="gallery">


                    <a href="/public/images/cerpadla/1.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/1.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/2.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/2.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/3.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/3.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/4.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/4.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/5.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/5.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/6.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/6.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/7.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/7.jpg" alt="text">
					</a>
                    <a href="/public/images/cerpadla/8.jpg" rel="lightbox[galerie1]">
						<img src="/public/images/cerpadla/8.jpg" alt="text">
					</a>



        </div>


    </div>


    <div class="text2">
        <p><img src="/public/images/pumpy.png" alt="pumpy"></p>
        <p>Věnujeme se jak prodeji nových pump, tak renovacím a opravám ručních pump, které už mají něco za sebou. Naši zákazníci jsou jak samotné domácnosti, tak chatkové a zahrádkářské osady po celém moravskoslezském kraji. Montujeme ruční pumpy dle pracovního válce až hloubky 30m.</p>
        <p>Ruční pumpy se používají k vyčerpávání vodních zdrojů jako jsou studny, vrty apod. Historicky se používali a stále používají v případech nedostupnosti elektrické energie.</p>
        <p>Pumpy, jejichž pracovní válec je umístěný v konstrukci samotného čerpadla jsou schopny vysát vodu z hloubky 7m. Pokud je vodní zdroj hlubší, je možno použít ruční pumpu typu Standart II, popřípadě Standart T, které se vyrábí po desetiletí v České republice.</p>
        
    
        <!--<a href="produkty/index">Nabídku našich čerpadel naleznete v kamenné prodejně, a již brzy taky na eshopu!</a>-->   
    
        
    </div>



    <div class="text3">
        <p><img src="/public/images/montaze-jimek-na-destovou-vodu-1.png" alt="asd"></p>
        <p>Montáž nádrží na dešťové vody provádíme napříč Moravskoslezským krajem a na Moravě.</p>
        <p>Zdarma Vám zhotovíme kalkulaci na dodávku a montáž jimky na dešťovou vodu včetně čerpací techniky.</p>
        <p>Pomoci z financováním koupě i montáže Vám mohou pomoci státem poskytované dotace. Například dotace dešťovka. I v tomto případě se na nás můžete obrátit a my po konzultaci s Vámi jsme schopni a ochotni pomoci od vypracování projektu, zajištění potřebných stanovisek dotčených orgánů, přes prodej, dodávku, až po samotnou montáž.</p>
        <p>Montáže jimek provádíme na klíč včetně výkopových prací. Jsme schopni proto garantovat vysokou kvalitu a bezproblémový chod celého ústrojí.</p>
   

        <div class="monolit">
            <h2>Monolitické jímky</h2>
             <p>Nabízíme kvalitní polyethylenové žebrované samonosné jímky, které se vyrábějí rotačním tvářením plastů HDPE vyrobené jedním z největší výrobců retenčních nádrží v Německu. Tato výrobní technologie zaručuje vodotěsnost, stabilitu a odolnost vůči vnějším vlivům. Použitý materiáůl samozřejmě nekoroduje a je receklovatelný.</p>
              <p>Životnost je ve své podstatě neomezena a je deklarována zárukou v podobě 20 let. Montáž je v nerizikových případech bez nutností obetonování, něco jiného je v případech zvýšené hladiny spodních vod apod.</p>
              <br>
             <p id="vyuziti">Využití nádrží:</p>
            <p>jako zdroj užitkové vody</p>
            <p>jako zdroj splaškové vody</p>
            <p>jako zdroj chemikálií</p>
             <br>
    
                <p>Při výrobě samotných nádrží je kladen důraz na moderní výrobní postupy, proto jsou také certifikované dle systému kvality EN ISO 9001 a splňují přísné evropské normy.</p>
            


        </div>

        <div class="svarene">
            <h2>Svařované jímky</h2>
            <p>Pokud potřebujete levnou, ale i přesto vysoce kvalitní jímku máme pro Vás řešení v podobě svařovaných jímek.</p>
            <p>Dodáváme a montujeme svařované jímky téměř všech místních výrobců v moravskoslezském kraji.</p>
            <p>Tyto jímky se vyznačují nižší cenovkou, vysokou nikoli však neomezenou životností. Neváhejte a poptejte si u nás jakoukoli jímku budete chtít, popřípadě si ji nechte individuálně navrhnout</p>
            <br><br>
            <!--<a href="produkty/index">Najdete na našem ESHOPU!</a>-->

            
        </div>

        <div class="gallery">


            <a href="/public/images/retencni-nadrze/1.jpg" rel="lightbox[galerie2]">
            <img src="/public/images/retencni-nadrze/1.jpg" alt="text">
            </a>
            <a href="/public/images/retencni-nadrze/2.jpg" rel="lightbox[galerie2]">
            <img src="/public/images/retencni-nadrze/2.jpg" alt="text">
            </a>
            <a href="/public/images/retencni-nadrze/3.jpg" rel="lightbox[galerie2]">
            <img src="/public/images/retencni-nadrze/3.jpg" alt="text">
            </a>
            <a href="/public/images/retencni-nadrze/4.jpg" rel="lightbox[galerie2]">
            <img src="/public/images/retencni-nadrze/4.jpg" alt="text">
            </a>
            <a href="/public/images/retencni-nadrze/5.jpg" rel="lightbox[galerie2]">
            <img src="/public/images/retencni-nadrze/5.jpg" alt="text">
            </a>
 

        </div>

   
        </div>


        <div class="text4">
            <p><img src="/public/images/filtry.png" alt="filtry"></p>
            <p>Při řešení vhodné filtrace vody vody bereme v potaz zápach vody, vodní kámen, zabarvení vody apod. Při následné analýze vody, která stanoví ať už chemickou, či mikrobakteriální závadnost vody jsme pro Vás schopni navrhnout vhodný typ úpravny vody. Této kapitole se více věnuje <a style="margin-left:0.1rem" href="uprava-vody">Úpravna vody.</a></p>
            <p>Filtry mechanických nečistot se používají jako předfiltry úpraven vod, popřípadě se instalují sólo. Vložky filtrů zachytávají mechanické nečistoty a odstraní tím problém se zacpávání potrubí, WC apod.</p>
            <p>Vhodný typ vložek do filtrů zaručuje vyčištění vody až do průmeru 5mcr. Různé typy vložek se používají na různé typy vod. Existují např. Vložky s aktivním uhlím, vložky naplněné polyfosfátem, aniontovou pryskyřicí apod.</p>
            <p>Speciální fitry mechanických nečistot se používají také na vodu teplou (tzn HOT FILTRY)</p>
            <p>Neječastěji se používají filtry plastové, ale v sortimentu jsou i filtry s mosaznou hlavou.</p>
            <p>Disponujeme kompletním sortimentem kvalitních výrobcem filtrů a vložek na mechanické nečistoty, například AQUA, či ATLAS FILTRI.</p>
            <p><img src="/public/images/filtry2.jpg" alt="filtry2"></p>
         
            <!--<a href="produkty/index">Najdete na našem ESHOPU!</a>-->
         </div>


         <div class="text5">
            <p><b style="color:#c60707; font-size:1.5rem">Provádíme kompletní realizace na klíč včetně samotného návrhu a výpočtu..</b></p>
            <p>Uvažujete-li o zdroji vody z vrtané studny, bude nutné vodotěsně a hygienicky zakončit vyústění vrtu. K tomu slouží tzv. zhlaví vrtané studny.</p>
            <p>Zhlaví vrtané studny lze vyřešit několika způsoby. Navrhneme Vám hned z několika variant plastových jímek dle prostředí vašeho vrtu.</p>
            <p>V případě těžkého terénu nebo umístění ve svahu, navrhneme Vám záhlaví vrtu pomocí betonových skruží s betonovým dnem. </p>
            <p>V případě plastových jímek se jedná o plastové samonosné, plastové s železo betonovým základem, plastové obetonované. Ve všech těchto variantách se jedná o  vodotěsnou šachtu, nasazenou na konec pažení vrtu, která slouží k uložení a přístupu k technologickým částem nutným pro čerpání vody z vrtané studny.</p>
            <p><img src="/public/images/zahlavi1.png" alt="filtry2"></p>
            <p>Vždy je důležité správně posoudit vaší horninu v okolí vašeho vrtu a skladbu vašich zemin, navrhnout správné .řešení na míru a vyvarovat se tak případným problémům v následném provozu. V případě špatně zvolné technologie, nebo nesprávně zvolená varianta samotné jímky, dochází k uvolňování, posunům, nebo k celkovému zničení.</p>
            <p><img src="/public/images/zahlavi2.jpg" alt="filtry2"></p>
            <p>V náročných terénech, či svazích, doporučujeme realizovat zhlaví vrtu pomocí betonových skruží. Důkladně se však musí myslet na zpevnění základny, tzv. plochy na kterou se ustavují skruže. Ve finále dojde k zabetonování dna s patřičným odvodem pro odtok případné srážkové vody uvnitř zhlaví.</p>
            <br><br>
            <h2 style="text-align: center;margin-bottom:4rem;font-size:2.5rem;font-family: 'Solitreo', cursive;color: #c60707;font-weight:600">Jaký je postup?</h2>
            <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">1.</span> Zaměření na stavbě</b></p>
            <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">2.</span> Zpracujeme technický návrh na míru </b></p>
            <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">3.</span> Cenová kalkulace na kompletní realizaci</b></p>
            <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">4.</span> Samotná realizace</b></p>
            <p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">5.</span> Uvedení do provozu</b></p>
       
            <div class="gallery">


<a href="/public/images/zahlavi-vrtu/1.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/1.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/2.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/2.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/3.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/3.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/4.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/4.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/5.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/5.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/6.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/6.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/7.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/7.jpg" alt="text">
</a>
<a href="/public/images/zahlavi-vrtu/8.jpg" rel="lightbox[galerie3]">
<img src="/public/images/zahlavi-vrtu/8.jpg" alt="text">
</a>

</div>
       
        </div>

         <div class="text6">
            <p><img width="450px" src="/public/images/domaci-vodarny/4.jpg" alt="vodarny"></p>
            <p>Domácí vodárny jsou zařízení, které jsou schopny při vhodné konfiguraci automaticky zásobovat objekty pitnou či užitkovou vodou</p>
            <p>Tvoříme domácí vodárny tak, abychom byli schopni zajistit dodávku vody z jakéhokoli vodního zdroje na jakékoli užití, ať už se jedná o zásobování objektů, postřiky zemědělských ploch, nebo zavlažování zahrad a tvorbu závlahových systémů.</p>
            <p>Vyzbrojujeme vrty a studny. Vybavujeme retenční nádrže čerpadly a tvoříme automatické domácí vodárny a posilovací stanice. Vhodnou řídící jednotkou čerpadla docílíme automatický provoz a zásobování vodou jakékoli odběrné místo, ať už se jedná o rodinný dům, firemní prostor nebo zahradu. Věnujeme se automatickým posilovacím stanicím v případě nízkého tlaku vody apod.</p>
            
            <p>Nabídku našich domácích vodáren naleznete jak v kamenné prodejně, a již brzy taky na eshopu!</p>
        
       


        <div class="gallery">


            <a href="/public/images/domaci-vodarny/1.jpg" rel="lightbox[galerie4]">
            <img src="/public/images/domaci-vodarny/1.jpg" alt="text">
            </a>
            <a href="/public/images/domaci-vodarny/2.jpg" rel="lightbox[galerie4]">
            <img src="/public/images/domaci-vodarny/2.jpg" alt="text">
            </a>
            <a href="/public/images/domaci-vodarny/3.jpg" rel="lightbox[galerie4]">
            <img src="/public/images/domaci-vodarny/3.jpg" alt="text">
            </a>
           


        </div>
        </div>



    </div>



<div class="bckbtn2" >
<a class="back" href="codelame">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>

</div>


<script src="/public/js/cerpadla.js"></script>
