<div class="welcomeimg2">

<h4><span>Individuální</span> přístup</h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
    <a class="soc-but">
    <i id="mobile" class="fa-solid fa-mobile-screen"></i>
    <i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


    <div class="welcome_logo">

        <img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

    </div>

    <div class="welcome_text">
        <h2 style="margin-bottom: 3px;">Servis a Opravy</h2>
        <p></p>
    </div>



    <div class="main_page_text" style="margin-top: 5rem; margin-bottom:3rem">
    <p>Zajišťujeme záruční opravy a zároveň provádíme pozáruční servis čerpací techniky prakticky všech výrobců, kteří poskytují na své produkty náhradní díly. Ať už se jedná o HOBBY čerpadla, nebo profesionální stroje, zakoupené u nás, nebo u jiných prodejců.</p>
    <p><b>Na opravy a servis poskytujeme dvouletou záruku.</b></p>
    <div class="img-mapa">
        <img src="/public/images/vyrobci.png" alt="mapa">
    </div>
    <p style="margin-top: 2rem;"><b>Opravy:</b></p>
    <p><strong>Ponorných čerpadel</strong></p>
    <p><strong>Zahradních čerpadel</strong></p>
    <p><strong>Kalových čerpadel</strong></p>
    <p><strong>Čerpadel do studní</strong></p>
    <p><strong>Čerpadel do vrtů</strong></p>
    <p><strong>Domácích vodáren</strong></p>    	

</div>

       
<div class="gallery">
<a href="/public/images/servis/11.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/11.jpg" alt="text">
</a>
<a href="/public/images/servis/12.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/12.jpg" alt="text">
</a>
<!--<a href="/public/images/servis/13.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/13.jpg" alt="text">
</a>
-->
<a href="/public/images/servis/1.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/1.jpg" alt="text">
</a>
<a href="/public/images/servis/2.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/2.jpg" alt="text">
</a>
<a href="/public/images/servis/3.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/3.jpg" alt="text">
</a>
<a href="/public/images/servis/4.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/4.jpg" alt="text">
</a>
<a href="/public/images/servis/5.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/5.jpg" alt="text">
</a>
<a href="/public/images/servis/6.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/6.jpg" alt="text">
</a>
<a href="/public/images/servis/7.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/7.jpg" alt="text">
</a>
<a href="/public/images/servis/8.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/8.jpg" alt="text">
</a>
<a href="/public/images/servis/9.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/9.jpg" alt="text">
</a>
<a href="/public/images/servis/10.jpg" rel="lightbox[galerie]">
<img src="/public/images/servis/10.jpg" alt="text">
</a>


</div>



<div class="bckbtn2" >
<a class="back" href="codelame">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>

</div>


<script src="/public/js/cerpadla.js"></script>
