
<div class="welcomeimg4">
	<h4>E-shop</h4>
	<div class="search-main">
		<a class="icon-search">
			<i id="lupa" class="fas fa-search"></i>
			<i id="lupa-close" class="fa-solid fa-xmark"></i>
		</a>
   		<form class="searching" role="search" method="POST">
        	<input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        	<button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    	</form>	
	</div>

</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

</div>

<div class="container">


    <div class="welcome_logo">

        <img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

    </div>


<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Nový E-shop již brzy!!!</h2>
<p></p>
</div>

<!--
<div class="main_page_text">
<h3 style="display:block;text-align:center;margin-bottom:2rem;">Do spuštení:</h3>

</div>

<div class="countdown" id="countdown">



<div class="time">
    <h5 id="days"></h5>
    <p>Dní</p>
</div>

<div class="time">
    <h5 id="hours"></h5>
    <p>Hodin</p>
</div>


<div class="time">
    <h5 id="minutes"></h5>
    <p>Minut</p>
</div>

<div class="time">
    <h5 id="seconds"></h5>
    <p>Sekund</p>
</div>



</div>-->


<div class="bckbtn">
<a class="back" href="codelame">Zpět</a>
<a class="back" href="uvod">Hllavní strana</a>
</div>

<script src="/public/js/odpocet.js"></script>