<div class="welcomeimg">

<h1><span>Čistá voda</span> od Beskyd po Jeseníky.</h1>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 


</div>
<div class="container">
<h3>Správa Objednávek</h3>
<table class="table table-bordered table-striped table-responsive-lg">
	<tr>
		<th>Datum</th>
		<th>Jméno</th>
		<th>Částka (bez DPH)</th>
		<th>Číslo faktury</th>
		<th>Stav</th>
	</tr>
	<?php foreach ($orders as $order) : ?>
		<tr data-order-id="<?= $order['e_order_id'] ?>" data-order-state="<?= $order['state'] ?>">
			<td class="align-middle"><?= FormatHelper::numericDate($order['created']) ?></td>
			<td class="align-middle"><?= PersonHelper::name($order) ?></td>
			<td class="align-middle"><?= FormatHelper::currency($order['price']) ?></td>
			<td class="align-middle">
				<a href="api/EshopModule-Products-OrderManagement/pdf/<?= $order['e_order_id'] ?>" class="invoice-link">
					<?= $order['number'] ?>
				</a>
				<a href="sprava-objednavek/manage/<?= $order['e_order_id'] ?>"><i class="fa fa-pencil-alt"></i></a>
			</td>
			<td class="change-state"></td>
		</tr>
	<?php endforeach ?>
</table>

</div>
<script src="js/order.state.editor.js"></script>