<!DOCTYPE html>
<html lang="cs">
	<head>
		<meta charset="utf-8" />
		<base href="http://<?= $domain ?>" />
		<link rel="stylesheet" href="css/style.css" type="text/css" />
		<link rel="stylesheet" href="css/forms.css" type="text/css" />
		<link rel="stylesheet" href="css/invoice.css" type="text/css" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

		<!-- Bootstrap Core CSS -->
		<link href="css/bootstrap.min.css" rel="stylesheet" />

		<!-- jQuery -->
		<script src="js/jquery.js"></script>
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css" />
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="js/bootstrap.min.js"></script>

		<script src="js/confirm.js"></script>
	</head>

	<body class="pt-0">
		<?php $controller->renderView() ?>
	</body>
</html>