<div class="welcomeimg">

<h1><span>Čistá voda</span> od Beskyd po Jeseníky.</h1>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">



<div class="container">
<table class="table table-bordered table-striped">
	<tr>
		<th>Platné od</th>
		<th>Platné do</th>
		<th>Sazba DPH</th>
		<th>Účetní</th>
		<th>Prodejce</th>
		<th>Podpis</th>
		<th></th>
	</tr>
	<?php foreach ($allSettings as $settings) : ?>
		<tr>
			<td><?= FormatHelper::numericDate($settings['valid_from']) ?></td>
			<td><?= FormatHelper::numericDate($settings['valid_to']) ?></td>
			<td><?= $settings['vat'] ?></td>
			<td><?= $settings['accountant'] ?></td>
			<td><?= $settings['seller'] ?></td>
			<td><img src="images/signatures/<?= $settings['settings_id'] ?>.png" alt="" /></td>
			<td>
				<a href="nastaveni/delete/<?= $settings['settings_id'] ?>" data-confirm="Opravdu si přejete odstranit nastavení pro dané období? (Při absenci nastavení se korektně nezobrazí staré objednávky)">
					<i class="fa fa-trash-alt"></i>
				</a>
			</td>
		</tr>
	<?php endforeach ?>
</table>

<?= $form->render() ?>
</div>