
<div class="welcome_logo">

<img class="logo_green" src="../../../../../public/images/logogreen.png" alt="logogreen"> 


</div>

<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Montáže jímek na dešťovou vodu</h2>
<p></p>
</div>


<div class="main_page_text">
<br><br>
    <img src="/public/images/jimky/montaze-jimek-na-destovou-vodu-1.png" alt="montaze">

<br><br><br><br><br><br>    
  <p>Montáž nádrží na dešťové vody provádíme napříč Moravskoslezským krajem a na Moravě.</p>
  <p>Zdarma Vám zhotovíme kalkulaci na dodávku a montáž jimky na dešťovou vodu včetně čerpací techniky.</p>
  <p>Pomoci z financováním koupě i montáže Vám mohou pomoci státem poskytované dotace. Například dotace dešťovka. I v tomto případě se na nás můžete obrátit a my po konzultaci s Vámi jsme schopni a ochotni pomoci od vypracování projektu, zajištění potřebných stanovisek dotčených orgánů, přes prodej, dodávku, až po samotnou montáž.</p>
  <p>Montáže jimek provádíme na klíč včetně výkopových prací. Jsme schopni proto garantovat vysokou kvalitu a bezproblémový chod celého ústrojí.</p>
  <p>Na montáže retenčních nádrží poskytujeme <b>2 letou záruku.</b></p>
</div>

<div class="odkaz1">


    <a id="monoliticke"><p>Monolitické</p><i id="krizek1" class="fas fa-times"></i></a>
    <a id="svarovane"><p>Svařované</p><i id="krizek2" class="fas fa-times"></i></a>
  
    




</div>








<div class="bckbtn2" >
<a class="back" href="montaze-servis">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>

</div>



<script src="/public/js/jimky.js"></script>