<div class="welcomeimg2">

<h4><span>Individuální</span> přístup</h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
    <a class="soc-but">
    <i id="mobile" class="fa-solid fa-mobile-screen"></i>
    <i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


    <div class="welcome_logo">

        <img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

    </div>


<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Čištění kopaných studní</h2>
<p>Čistá voda – čistý život</p>
</div>


<div class="main_page_text">
<p>Mít v dnešní době vlastní zdroj vody, je jako na zahradě mít zlatý důl. Ať už vodu ze studen využíváte jako užitkovou, nebo pitnou je třeba se o ni náležitě starat.</p>  
<p><b>Svěřte Vaší studnu odborníkům, kteří se postarají o to, ať je voda ve Vaší studni čistá.</b></p>
<p>Provádíme odborné čištění kopaných studen <b>do hloubky 20 m</b> za použití profesionální techniky.</p>
<p>U kopaných studen se časem projevuje přirozené znečištění. To má za následek devastaci čerpadel, sacích košů které měníte každou chvíli, snižování vodního sloupce, v nejhorším případě úplné vyschnutí studny.</p>
<p>Příčiny zanášení studen jsou různé. Může jít o dešťové vody, které naplavují biologický materiál a jiné nečistototy, kontaminace způsobená průsakem vody odpadní z kanalizací, či septiků, nebo konrtaminace chemických postřiků z polí apod.</p>
<p>Pokud Vaše studna nemá dostatečný přítok, ve většině případů se jedná o zanesení nátoků nečistotami. Ty se za dobu používaní, či nepoužívání studny dostali do míst, kudy proudil pramen, který se tím mohl odklonit.</p>
<p><b>Studny, které jímají vodu pouze dnem, se během pár let zanesou vysokou vrstvou nečistot. Nejčastěji se jedná o bahno, kaly, kusy dřev a kovů, mrtvé živočichy, které zabraňují pronikání vody do Vašeho zdroje.</b></p>
<p>Nedovedete si představit co všechno jsme už ze studen vytáhli.</p>
<p><b>I studny se stále vysokým přítokem je třeba pravidelně čistit z důvodů kontaminace vody, která způsobuje jak už ničení čerpadel umístěných ve studni, tak Vaše zdraví. Díky mechanickému čištění vysokoprůtokovým čerpadlem si poradíme i s velkými přítoky!</b></p>
<p>V případě zájmu Vám můžeme zprostředkovat rozbor vody.</p>
<p>Čištění studen provádíme v celém Moravskoslezském kraji a na Moravě. Cena za čištění může být různá, podle typu a hloubky studny a rozsahu prací. Neváhejte a nechte si zpracovat cenovou nabídku.</p>
<br>
<h2 style="text-align: center;margin-bottom:4rem;font-size:2.5rem;font-family: 'Solitreo', cursive;color: #c60707;font-weight:600">Jaký je postup?</h2>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">1.</span>&nbsp&nbsp&nbsp&nbspOdčerpání vody ve studni</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">2.</span>&nbsp&nbsp&nbsp&nbspMechanické vyčištění viditelných usazenin jak ze dna, tak ze skruží</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">3.</span>&nbsp&nbsp&nbsp&nbspUmytí skruží studny vysokotlakovou horkou vodní Vapkou</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">4.</span>&nbsp&nbsp&nbsp&nbspChemické vyčištění, které odstraní škodlivé bakterie</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">5.</span>&nbsp&nbsp&nbsp&nbspVysypání stávajícího dna novým kačírkem</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">6.</span>&nbsp&nbsp&nbsp&nbspUvedení zpět do provozu</b></p>
<br><br>
<p>V případě že rozsah čištění, se bude lišit od toho základního, bude upravena cena po dohodě s Vámi.</p>
</div>


<div class="gallery">


                    <a href="/public/images/cisteni-kopanych-studni/1.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/1.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/2.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/2.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/3.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/3.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/4.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/4.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/5.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/5.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/6.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/6.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/7.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/7.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/8.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/8.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/9.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/9.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/10.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/10.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/11.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/11.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/12.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/12.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/13.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/13.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/14.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/14.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/15.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/15.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/16.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/16.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/17.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/17.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/18.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/18.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-kopanych-studni/19.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-kopanych-studni/19.jpg" alt="text">
					</a>
                
                    



</div>




<div class="bckbtn">
<a class="back" href="codelame">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>
</div>