<div class="welcomeimg3">

<img src="/public/images/novazelena.png" alt="">
<h4>Dotační programy <span>na klíč!</span> </h4>

</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line">

</div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

</div>


<div class="welcome_text">
<h2>Dotace</h2>
<p></p>
</div>


<div class="main_page_text">
    <p>Zajištujeme program dešťovka od projektové dokumentace, přes realizaci, až po uvedení do provozu a vyřízení dotace od Fondu životního prostředí.</p>
    <p><b>Mezi naše programy patří:</b></p>
</div>



<div class="odkaz1">

    <a href="destovka" id="destovka"><p>dešťovka</p></a>
    <a href="destovka-a-cov" id="destovka2"><p>dešťovka&nbsp+&nbspčov</p></a>


    <!-- !!!!!!!!!!!!!!DEstovka + cov dodelat stranku under reconstruction!!!!!!!!!!!!!!!!!-->


</div>
<br><br><br>



<div class="bckbtn2" >

<a class="back" href="uvod">Hlavní strana</a>

</div>