<div class="welcomeimg">

<h1><span>Čistá voda</span> od Beskyd po Jeseníky.</h1>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 


</div>

<div class="welcome_text">
<h2>Kontakty</h2>

</div>


<div class="adresy">
    <div class="adresa1">
        <h2>Prodejna čerpadel Příbor</h2>
        <h3>Adresa:</h3>
        <p>Karla Čapka 58</p>
        <p>742 58 Příbor</p>
        <p>Česko</p>
        <br>
        <h3>Telefon:</h3>
        <a href="tel:+420 725 513 733">+420 725 513 733</a>
        <br><br>
        <h3>E-mail:</h3>
        <a href="mailto:pribor@cerpadla-studny.cz">pribor@cerpadla-studny.cz</a>
        <br><br>
        <h3>Otevírací doba:</h3>
        <p><b>Po – Čt:</b> 8:30–16:00</p>
        <p><b>Pá:</b> 8:30–15:00</p>
        <p><b>So – Ne:</b> Zavřeno</p>
        <iframe id="google" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2583.726092808232!2d18.137992630580232!3d49.64061681339252!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4713edeaa76df905%3A0x4f72ed3fb3ab2023!2zS2FybGEgxIxhcGthIDU4LCA3NDIgNTggUMWZw61ib3I!5e0!3m2!1scs!2scz!4v1674479171207!5m2!1scs!2scz" width="450" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="adresa2">
        <h2>Prodejna čerpadel Opava</h2>
        <h3>Adresa:</h3>
        <p>K Zátiší 323</p>
        <p>747 69, Pustá Polom</p>
        <p>Česko</p>
        <br>
        <h3>Telefon:</h3>
        <a href="tel:+420 725 890 800">+420 725 890 800</a>
        <br><br>
        <h3>E-mail:</h3>
        <a href="mailto:opava@cerpadla-studny.cz">opava@cerpadla-studny.cz</a>
        <br><br>
        <h3>Otevírací doba:</h3>
        <p id="cesko">Na zavolání.</p>
        <iframe id="google" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2572.500237064418!2d18.00302441559823!3d49.851847279397305!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4713ddd55ff728a7%3A0xa86f1f96f1192326!2zSyBaw6F0acWhw60gMzIzLCA3NDcgNjkgUHVzdMOhIFBvbG9t!5e0!3m2!1scs!2scz!4v1674479243487!5m2!1scs!2scz" width="450" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>



<div class="mapy">
    <div class="mapa1"></div>


    <div class="mapa2"></div>
</div>


<div class="adresy">
<h3 style="margin-bottom: -2rem;">Nebo využijte kontaktní formulář:</h3>
</div>
<?= $form->render() ?>