<div class="welcomeimg">

<h1><span>Čistá voda</span> od Beskyd po Jeseníky.</h1>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 


</div>

<p id="admin_wlc">Vítejte v administraci, jste přihlášeni jako <br><span><?= $email ?></span></p>

<nav class="administration">
	<div class="admin1">
	<a href="osoby/manage">Správa údajů</a>
	<?php if ($admin) : ?>
		<a href="sprava-objednavek">Správa objednávek</a>
		<a href="produkty/manage">Přidat produkt</a>
		<a href="sprava-kategorii">Správa kategorií</a>
		<a href="nastaveni">Nastavení</a>
	<?php endif ?>
	<a href="administrace/logout">Odhlásit</a></div>
</nav>