<div class="welcomeimg2">

<h4><span>Individuální</span> přístup</h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
    <a class="soc-but">
    <i id="mobile" class="fa-solid fa-mobile-screen"></i>
    <i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


    <div class="welcome_logo">

        <img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

    </div>


<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Čištění vrtaných studní</h2>
<p>Čistá voda – čistý život</p>
</div>


<div class="main_page_text">
<p>Provádíme čištění hlubinných vrtů až do hloubky 100m jakéhokoliv průměru pažnice.</p>
<p>Přítoky podzemní vody sebou přirozeně přináší drobné částice zemin, které se postupně usazují na dně vrtu a zanášejí kalník. Tento sediment může v průběhu let nastoupat i v řádech metrů a v nejhorších případech i zcela spolkout čerpadlo.</p>
<p>Proto je důležité provádět čištění vrtů v pravidelných intervalech 5-7 let. Špatná kvalita vody může vézt k častým problémům s ponornými čerpadly. Zhoršená kvalita a čerstvost vody v podobě přemnožených bakterií je pravidelným čištěním také eliminována.</p>
<p style="margin-top: 4rem;"><b style="color: #00288d;font-size:1.2rem;">1. AIRLIFTOVÁ METODA:</b></p>
<p>Tato metoda čištění vrtu spočívá ve vhánění vzduchu vysokotlakým kompresorem, který na dně víří usazený sediment. Nečistoty jsou následně odváděny druhým potrubím ven. Tímto způsobem jsme schopni odstranit jak hrubé nečistoty, tak i jemný písek, který způsobuje vydírání mechanických částí čerpadel.</p>
<p style="margin-top: 4rem;"><b style="color: #00288d;font-size:1.2rem;">2. ČERPACÍ METODA</b></p>
<p>Do vrtané studny je instalováno speciální čerpadlo, které je schopno odčerávat znečištěnou vodu z vrtu ven.</p>
<p style="margin-top: 4rem;"><b style="color: #00288d;font-size:1.2rem;">3. KOMBINACE</b></p>
<P>Airliftem odstraníme hrubé nečistoty ze dna vrtu a následně rozvířený vrt plynule odčerpáváme speciálním čerpadlem, které nám pomůže vrt stabilizovat a šetrně odčerpat zbylé nečistity.</P>
<br><br>
<h2 style="text-align: center;margin-bottom:4rem;font-size:2.5rem;font-family: 'Solitreo', cursive;color: #c60707;font-weight:600">Jaký je postup?</h2>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">1.</span> Demontáž a odpojení stávajícího čerpadla</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">2.</span> Provedení čerpací zkoušky</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">3.</span> Vyčištění vrtu jednou z výše uvedených metod na základě zaměření vrtu</b></p>
<p style="font-size:1.5rem"><b><span style="font-size:2rem;color: #c60707;">4.</span> Zpětné ustavení čerpací techniky a uvedení do provozu</b></p>


</div>


<div class="gallery">


                    <a href="/public/images/cisteni-vrtanych-studni/1.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/1.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/2.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/2.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/3.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/3.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/4.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/4.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/5.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/5.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/6.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/6.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/7.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/7.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/8.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/8.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/9.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/9.jpg" alt="text">
					</a>
                    <a href="/public/images/cisteni-vrtanych-studni/10.jpg" rel="lightbox[galerie]">
						<img src="/public/images/cisteni-vrtanych-studni/10.jpg" alt="text">
					</a>
                   

</div>


<div class="bckbtn">
<a class="back" href="codelame">Zpět</a>
<a class="back" href="uvod">Hllavní strana</a>
</div>