<div class="welcomeimg3">
<img src="/public/images/novazelena.png" alt="">
<h4>Dotační programy <span>na klíč!</span> </h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

</div>

<div class="welcome_text">
<h2 style="margin-bottom: 3px;">Dešťovka + ČOV</h2>
<p></p>
</div>


<div class="main_page_text">
   <H3 style="text-align:center;">Již brzy!!!</H3>
</div>


<div class="bckbtn">
<a class="back" href="programy">Zpět</a>
<a class="back" href="uvod">Hlavní strana</a>
</div>