<div class="welcomeimg2">

<h4><span>Individuální</span> přístup</h4>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 

</div>

<div class="welcome_text">
<h2>Co děláme?</h2>
<p></p>
</div>


<div class="main_page_text" style="margin-bottom: 2rem;">

<p>Věnujeme se komplexním službám v oboru nakládání s vodami</p>
<p><b style="color: #c60707;">Zajišťujeme pro Vás prodej, montáž a servis námi nabízených čerpadel.</b></p>
<p>Naše práce začíná samotným čištěním vodních zdrojů, provádíme čerpací zkoušky, instalujeme záhlaví vrtů, vyzbrojujeme studny a vrty naší čerpací technikou, děláme studniční práce. Na naše namontovaná čerpadla poskytujeme pozáruční servis.</p>
<p>Pomůžeme Vám s filtrací a úpravou vody samotné, od rozboru vody až po instalaci vhodného filtračního zařízení.</p>
<p>Pracujeme s využitím dešťových vod, instalujeme nádrže. Jsme schopni Vám zajistit dotační program na klíč.</p>
<p>Podzemní a srážkové vody jsou najdou využití jak v zásobování objektů, tak zavlažování zahrad rodinných domů, firemních areálů, či sportovišť. Samostatnou kapitolu zavlažování najdete níže.</p>

</div>



<div class="odkaz2">


    <a href="montaze" id="montaze"><p>montáže</p></a>
    <a href="servis" id="btn-servis"><p>servis</p></a>
    <a href="cisteni-vrtu" id="cisteni-vrtu"><p>čištění&nbspvrtů</p></a>
    <a href="cisteni-studni" id="cisteni-studni"><p>čištění&nbspstudní</p></a>   
    <a href="uprava-vody" id="uprava-vody"><p>úpravna&nbspvody</p></a>
    <a href="https://zavlazimeto.cz/" id="zavlazovani"><p>zavlažování</p></a>             
    




</div>


<div class="bckbtn">

<a class="back" href="uvod">Hlavní strana</a>

</div>