<div class="welcomeimg">

<h1><span>Čistá voda</span> od Beskyd po Jeseníky.</h1>
    <!---<form class="searching" role="search" method="POST">
        <input name="search-phrase" type="search" value="<?= $_GET['phrase'] ?? '' ?>" placeholder="Hledejte zboží na našem E-shopu.." aria-label="Product title">
        <button class="hledac" type="submit"><i class="fas fa-search"></i></button>
    </form>	-->


</div>
<div class="social">
<a class="soc-but">
<i id="mobile" class="fa-solid fa-mobile-screen"></i>
<i id="close-mobile" class="fa-solid fa-xmark"></i>
</a>
<a class="fb" href="https://www.facebook.com/cerpadlastudny"><i class="fa-brands fa-square-facebook"></i></a>
<a class="phone" href="https://wa.me/420725890800"><i class="fa-brands fa-square-whatsapp"></i></a>
<a class="mail"	href="mailto:pribor@cerpadla-studny.cz"><i class="fa-solid fa-square-envelope"></i></a>
</div>
<div class="green_line"></div>

</div>

<div class="container">


<div class="welcome_logo">

<img class="logo_grey" src="../../../../../public/images/logo.png" alt="logogreen"> 


</div>


<?= $form->renderStartForm() ?>
<?= $form->renderControls('product_id', 'code', 'url', 'title', 'short_description', 'description') ?>

<?php if ($product) : ?>
	<div id="product-images-administration">
		<?php for ($i = 0; $i < $product['images_count']; $i++) : ?>
			<div>
				<img src="images/products/<?= $product['product_id'] ?>_<?= $i ?>.jpg?timestamp=<?= time() ?>" alt="" />
				<a href="api/EshopModule-Products-Product/delete-image/<?= $product['product_id'] ?>/<?= $i ?>"><i class="fa fa-trash-alt"></i></a>
			</div>
		<?php endfor ?>
	</div>
<?php endif ?>
<?= $form->renderControls('images[]', 'categories[]', 'price', 'old_price') ?>

<?= $form->renderButtons() ?>
<?= $form->renderEndForm() ?>


<script src="https://cdn.tiny.cloud/1/nrocs62u3auwxspiu5pyfibib1608fz4uwomh59gn7telies/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
      toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
    });
  </script>
<script type="text/javascript" src="js/image.administration.js"></script>
